:Author: me
:Email: {AuthorEmail}
:Date: 16/11/2018
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Inputs-product                => Arduino sketch folder
  ├── Produto das entradas.ino                     => main Arduino file
  ├── Circuito base.png                            => an image of the circuit which is very similar to the one required
  ├── Circuito display sete segmentos.png          => an image focused on the Seven Seg Display connections
  └── ReadMe.adoc                                  => this file
....

=== License
This project is released under a License.

=== Contributing
To contribute to this project please contact me.

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name                             | Part number | Quantity
| R1 | 1k Resistor                           | 1234-abcd   | 4
| L1 | 7 Segment Displays (Common Cathode)   | 2345-asdf   | 2
| A1 | Arduino Uno                           | ABX00066    | 1
| C1 | CD 4511 - BCD to 7 Display Decoder    | XXXXXXXX    | 2
| C1 | Push buttons                          | XXXXXXXX    | 2
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
